feat: FV-52 - adds kick and ban system
FallenVaders/mc-fallenvaders pull request #5
Opened 2021-08-15 11:50 UTC by GlynixFR

2021-08-15 17:18 UTC, Voltariuss requested changes

2021-08-15 17:18 UTC, Voltariuss commented on libraries/justice-hands/src/main/java/fr/fallenvaders/minecraft/justice_hands/keyskeeper/listeners/PlayerLoginListener.java
>              e.allow();
Même logique que pour le return `e.setCancelled(false)`, 1) on a aucun intérêt à autoriser un joueur à se connecter sur le serveur : par défaut c'est déjà le cas 2) on risque de rentrer en conflit avec d'autres modules/plugins inutilement.

2021-08-15 17:18 UTC, Voltariuss commented on libraries/justice-hands/src/main/java/fr/fallenvaders/minecraft/justice_hands/keyskeeper/listeners/PlayerLoginListener.java
> +            e.disallow(PlayerLoginEvent.Result.KICK_BANNED, KeysKeeperComponent.loginBanMessage(playerLongestBan));
En lien avec le refactoring de la classe `KeysKeeperComponent`, refactorer les deux conditions pour n'avoir qu'un simple `if (playerLongestBan.getTSExpireDate() == null || playerLongestBan.getTSExpireDate().getTime() > System.currentTimeMillis()) { ... }` quitte à rajouter une variable booléenne `isBanDef = playerLongestBan.getTSExpireDate() == nul`.

2021-08-15 17:18 UTC, Voltariuss commented on libraries/justice-hands/src/main/java/fr/fallenvaders/minecraft/justice_hands/keyskeeper/listeners/PlayerLoginListener.java
>              e.allow();
Idem ici, à supprimer

2021-08-15 17:18 UTC, Voltariuss commented on libraries/justice-hands/src/main/java/fr/fallenvaders/minecraft/justice_hands/sanctionmanager/invmanager/CategoryInventorySM.java
> +                            KeysKeeperBot.kickPlayer(Bukkit.getPlayer(UUID.fromString(inventory.getId())), JusticeHands.getSqlSM().getLastSanction(Bukkit.getPlayer(UUID.fromString(inventory.getId()))
Alors, ça peut toujours se discuter, mais personnellement je suis plus de l'école où on déclare toutes les variables dont on a besoin avant de les utiliser. Ca permet de simplifier le debugging lorsqu'on passe en mode pas à pas. Puis ça allège les instructions.

2021-08-15 17:18 UTC, Voltariuss commented on libraries/justice-hands/src/main/java/fr/fallenvaders/minecraft/justice_hands/sql/SqlSanctionManager.java
> +        return null;
Suivant si les fonctions peuvent retourner `null` ou pas, il est préférable de modifier la signature de la fonction pour intégrer des annotations `@NotNull` et `@Nullable` comme c'est proposé par la librairie d'annotation Java de Jetbrains : https://www.jetbrains.com/help/idea/nullable-and-notnull-annotations.html

2021-08-15 17:18 UTC, Voltariuss commented on libraries/justice-hands/src/main/java/fr/fallenvaders/minecraft/justice_hands/sql/SqlSanctionManager.java
> +        return null;
Ca permet d'indiquer aux consommateurs de la fonction s'ils doivent gérer le cas du `null` ou pas.

2021-08-15 17:18 UTC, Voltariuss commented on libraries/justice-hands/src/main/java/fr/fallenvaders/minecraft/justice_hands/sql/SqlSanctionManager.java
> +            while (rs.next()) {
Je pense qu'ici on peut simplifier le code en utilisant la méthode `first()` de `ResultSet` pour supprimer l'instruction `while` qui peut induire en erreur quand au nombre de résultats attendus : https://docs.oracle.com/javase/7/docs/api/java/sql/ResultSet.html#first()

2021-08-28 15:17 UTC, GlynixFR commented on libraries/justice-hands/src/main/java/fr/fallenvaders/minecraft/justice_hands/keyskeeper/KeysKeeperBot.java
> +        if (muteDateTSList.size() > 0) {
J'ai pas très bien compris ton explication, mais le but de ma méthode est de récupérer la valeur la plus élevée dans une liste de Long. J'ai mis le try catch

2021-08-28 15:22 UTC, GlynixFR commented on libraries/justice-hands/src/main/java/fr/fallenvaders/minecraft/justice_hands/keyskeeper/listeners/AsyncChatListener.java
> +            e.setCancelled(false);
Lors de la méthode qui récupère le mute le plus long du joueur (ligne 13) j'ai fait en sorte que si le joueur n'a jamais eu de mute, que cette dernière retourne 0. Ce qui me permet de sortir les null de cette partie

2021-08-28 15:24 UTC, GlynixFR commented on libraries/justice-hands/src/main/java/fr/fallenvaders/minecraft/justice_hands/keyskeeper/KeysKeeperComponent.java
> +public class KeysKeeperComponent {
j'ai pas compris ce que tu voulais que je fasse ici lol

2021-08-28 15:39 UTC, GlynixFR commented on libraries/justice-hands/src/main/java/fr/fallenvaders/minecraft/justice_hands/keyskeeper/KeysKeeperComponent.java
> +                "\n§bTemps restant : §7" + GeneralUtils.timeRemaining(sanction.getTSExpireDate().getTime()-System.currentTimeMillis())
sera fait sur le prochain commit

2021-08-28 15:39 UTC, GlynixFR commented on libraries/justice-hands/src/main/java/fr/fallenvaders/minecraft/justice_hands/keyskeeper/KeysKeeperComponent.java
> +public class KeysKeeperComponent {
sera fait sur le prochain commit

2021-08-28 15:41 UTC, GlynixFR commented on libraries/justice-hands/src/main/java/fr/fallenvaders/minecraft/justice_hands/keyskeeper/KeysKeeperComponent.java
> +            String.format(GeneralUtils.getPrefix("kk") +
Bon en gros supprimer les + par des ,

2021-08-28 20:23 UTC, GlynixFR commented
@Voltariuss

2021-08-29 08:13 UTC, Voltariuss approved these changes

2021-08-29 08:13 UTC, Voltariuss commented on libraries/justice-hands/src/main/java/fr/fallenvaders/minecraft/justice_hands/keyskeeper/KeysKeeperComponent.java
> +public class KeysKeeperComponent {
Juste un commentaire, pas d'action à réaliser

2021-08-29 08:13 UTC, Voltariuss commented on libraries/justice-hands/src/main/java/fr/fallenvaders/minecraft/justice_hands/sql/SqlKeysKeeper.java
>      public List<Long> getPlayerMutesEDLong(Player player) {
Pour une liste, généralement on préfère retourne une liste vide plutôt qu'une liste nulle.

2021-08-29 15:50 UTC, GlynixFR reviewed
Conflict correction from previous merge (FV-53 into develop)

2021-08-29 15:50 UTC, merged