feat: FV-55 - correct transactions support
FallenVaders/mc-fallenvaders pull request #6
Opened 2021-08-15 12:49 UTC by bletrazer

- Modification of model to correctly support transactions.
 - Connections are now created and closed for each queries.

2021-08-15 18:45 UTC, Voltariuss requested changes

2021-08-15 18:45 UTC, Voltariuss commented on libraries/mail-box/src/main/java/fr/fallenvaders/minecraft/mail_box/sql/BaseSQL.java
> +    public T create(T obj, boolean autoCommit) {
autoCommit n'est jamais utilisé

2021-08-15 18:45 UTC, Voltariuss commented on libraries/mail-box/src/main/java/fr/fallenvaders/minecraft/mail_box/sql/BaseSQL.java
> +        this.sqlConnection.disconnect();
Avant de clore la connexion, rollback ou commit la transaction.

Ce que dit à la doc de `Connection#disconnect()` : "It is strongly recommended that an application explicitly commits or rolls back an active transaction prior to calling the close method. If the close method is called and there is an active transaction, the results are implementation-defined." -> https://docs.oracle.com/javase/7/docs/api/java/sql/Connection.html#close()

2021-08-15 18:45 UTC, Voltariuss commented on libraries/mail-box/src/main/java/fr/fallenvaders/minecraft/mail_box/sql/BaseSQL.java
> +    protected abstract Boolean onDelete(T obj);
Idem, pourquoi Boolean et pas boolean ?

2021-08-15 18:45 UTC, Voltariuss commented on libraries/mail-box/src/main/java/fr/fallenvaders/minecraft/mail_box/sql/DataSQL.java
> +            ResultSet resultset = query.executeQuery();
Idem, `resultSet`

2021-08-15 18:45 UTC, Voltariuss commented on libraries/mail-box/src/main/java/fr/fallenvaders/minecraft/mail_box/sql/ItemDataSQL.java
> +                PreparedStatement query = this.sqlConnection.getConnection().prepareStatement("UPDATE " + TABLE_NAME + " SET uuid = ?, itemStack = ?, durationInSeconds = ? WHERE id = ?");
Clore la prepareStatement dans le bloc finally du try catch finally pour être sûr de la clore même en cas de levée d'exception

2021-08-15 18:45 UTC, Voltariuss commented on libraries/mail-box/src/main/java/fr/fallenvaders/minecraft/mail_box/sql/LetterDataSQL.java
> +                .prepareStatement("CREATE TABLE IF NOT EXISTS	" + TABLE_NAME + " (id BIGINT, uuid VARCHAR(255), type VARCHAR(255), content TEXT, isRead BOOLEAN DEFAULT '0', PRIMARY KEY(id))");
Idem, longueur de ligne

2021-08-16 11:22 UTC, bletrazer commented on libraries/mail-box/src/main/java/fr/fallenvaders/minecraft/mail_box/data_manager/MailBoxController.java
>          while (it.hasNext() && !error) {
Fait: j'utilise Stream.filter() pour récupérer les données à effacer, deleteAll() pour les supprimer

2021-08-16 11:23 UTC, bletrazer commented on libraries/mail-box/src/main/java/fr/fallenvaders/minecraft/mail_box/data_manager/MailBoxController.java
>      public static Boolean sendLetter(Player player, LetterData letterData) {
Fait: j'ai changer tout les Objets Boolean Integer par leurs primitifs "boolean" et "int".

2021-08-16 12:08 UTC, bletrazer commented on libraries/mail-box/src/main/java/fr/fallenvaders/minecraft/mail_box/inventory/inventories/ItemInventory.java
> +        if (this.getDataSource().getOwnerUuid().equals(player.getUniqueId()) && player.hasPermission("mailbox.item.delete.self") || player.hasPermission("mailbox.item.delete.other")) {
Je suis repassé sur mes classes et j'ai réduits la longueur des plus grandes lignes

2021-08-16 12:09 UTC, bletrazer commented on libraries/mail-box/src/main/java/fr/fallenvaders/minecraft/mail_box/player_manager/PlayerInfo.java
> +
J'ai retiré un max de ligne vide xD

2021-08-16 12:09 UTC, bletrazer commented on libraries/mail-box/src/main/java/fr/fallenvaders/minecraft/mail_box/player_manager/PlayerInfoSQL.java
> +        Integer check = this.check(PI);
Modifié

2021-08-16 12:09 UTC, bletrazer commented on libraries/mail-box/src/main/java/fr/fallenvaders/minecraft/mail_box/player_manager/PlayerInfoSQL.java
> +            ResultSet resultset = query.executeQuery();
Modifié

2021-08-16 12:13 UTC, bletrazer commented on libraries/mail-box/src/main/java/fr/fallenvaders/minecraft/mail_box/sql/BaseSQL.java
> +        this.sqlConnection.disconnect();
Modifié: dans ma classe BaseSQL les méthodes create, update, delete et leurs version "all" j'ai rajouté un rollback dans le cas ou l'action onCreate/onUpdate/onDelete retourne une valeur null (elles retournent null dans le cas ou il y a eu un problème).

2021-08-16 12:14 UTC, bletrazer commented on libraries/mail-box/src/main/java/fr/fallenvaders/minecraft/mail_box/sql/ItemDataSQL.java
> +                PreparedStatement query = this.sqlConnection.getConnection().prepareStatement("UPDATE " + TABLE_NAME + " SET uuid = ?, itemStack = ?, durationInSeconds = ? WHERE id = ?");
Fait

2021-08-16 12:18 UTC, bletrazer commented
Il manque plus qu'a modifier les code couleurs "§x" par ChatColor. et tout est bon.

2021-08-24 15:10 UTC, Voltariuss commented on libraries/mail-box/src/main/java/fr/fallenvaders/minecraft/mail_box/data_manager/MailBoxController.java
>          while (it.hasNext() && !error) {
Changements non visibles (est-ce que t'as push ?)

2021-08-24 16:31 UTC, Voltariuss approved these changes

2021-08-24 16:35 UTC, merged