feat: FV-53 - adds points configuration system
FallenVaders/mc-fallenvaders pull request #7
Opened 2021-08-15 14:52 UTC by GlynixFR

2021-08-24 15:26 UTC, Voltariuss requested changes

2021-08-24 15:26 UTC, Voltariuss commented on plugin/src/main/resources/config.yml
> +        # Pour un mute,par défaut  chaque point vaut 1 minute :
Un p'tit espace oublié

2021-08-24 15:26 UTC, Voltariuss commented on libraries/justice-hands/src/main/java/fr/fallenvaders/minecraft/justice_hands/sanctionmanager/SanctionsAlgo.java
> +        String pointConfigurationPath = "justicehands.sanctionmanager.points-system";
Constant

2021-08-24 15:26 UTC, Voltariuss commented on libraries/justice-hands/src/main/java/fr/fallenvaders/minecraft/justice_hands/sanctionmanager/SanctionsAlgo.java
> +        int muteMinPerPts = config.getInt(pointConfigurationPath + ".mute-min-points");
Tu peux également former 3 constantes supplémentaires, toutes étant basées sur la première.

2021-08-24 15:26 UTC, Voltariuss commented on libraries/justice-hands/src/main/java/fr/fallenvaders/minecraft/justice_hands/sanctionmanager/SanctionsAlgo.java
> +        int muteMinPerPts = config.getInt(pointConfigurationPath + ".mute-min-points");
Genre `public static final String CFG_PATH_BAN_DAY_POINT = CFG_PATH_POINT + ".ban-day-points";`

2021-08-24 15:26 UTC, Voltariuss commented on libraries/justice-hands/src/main/java/fr/fallenvaders/minecraft/justice_hands/sanctionmanager/SanctionsAlgo.java
> +        if (targetPoints >= risingbanLimit && !(tempSanction.getInitialType().equals("ban") || tempSanction.getInitialType().equals("bandef"))) {
Une bonne pratique dans l'utilisation de la méthode `equals()`, c'est de l'appeler à partir de la constante alors qu'en passant par un objet potentiellement `null` on prend le risque de se chopper un `NullPointerException` bêtement. Ici ce n'est pas grave puisque le code dans son ensemble est contrôlé, mais dans des situations on peut avoir un doute sur ce qu'on manipule c'est mieux d'opter pour l'approche évoquée.

Au lieu de :
`tempSanction.getInitialType().equals("ban")`
Faire :
`"ban".equals(tempSanction.getInitialType())`

2021-08-24 15:26 UTC, Voltariuss commented on libraries/justice-hands/src/main/java/fr/fallenvaders/minecraft/justice_hands/sanctionmanager/SanctionsAlgo.java
> +        final long longMin = 60l*1000l; // sec(60) * ms(1000)
On préfère les espaces entre les opérandes et les opérateurs => `601 * 10001` (google-java-format le fait automatiquement en passant par le plugin IntelliJ)

2021-08-28 13:12 UTC, GlynixFR commented on libraries/justice-hands/src/main/java/fr/fallenvaders/minecraft/justice_hands/sanctionmanager/SanctionsAlgo.java
> +        if (targetPoints >= risingbanLimit && !(tempSanction.getInitialType().equals("ban") || tempSanction.getInitialType().equals("bandef"))) {
J'apprécie la remarque ! C'est un très bon conseil qui évite des lignes supplémentaire

2021-08-28 13:26 UTC, GlynixFR commented
@Voltariuss requested changes done

2021-08-28 13:39 UTC, Voltariuss requested changes

2021-08-28 13:39 UTC, Voltariuss commented on libraries/justice-hands/src/main/java/fr/fallenvaders/minecraft/justice_hands/sanctionmanager/SanctionsAlgo.java
> +    final String CFG_PATH_POINT = "justicehands.sanctionmanager.points-system";
Tu as mal compris ce que je voulais que tu fasse : relis mon précédent commentaire sur le sujet parce que :
1) C'est la chaîne de caractères à mettre dans une constante
2) Une constante, c'est forcément un `public static final <type> <variable> = <value>` : c'est une variable de classe.
3) Seules les constantes doivent être écris en UPER_CASE. Et si la constante n'est pas une variable de classe, alors elle doit le devenir.

2021-08-28 15:46 UTC, Voltariuss requested changes

2021-08-28 15:46 UTC, Voltariuss commented on libraries/justice-hands/src/main/java/fr/fallenvaders/minecraft/justice_hands/sanctionmanager/SanctionsAlgo.java
> +    public static final FileConfiguration CONFIG = JusticeHands.PLUGIN.getConfig();
Ça ne fonctionnera pas. Si la classe est chargée avant que la méthode onEnable du plugin a été chargé la variable JusticeHands.PLUGIN sera null, donc NullPointerException.

Pour l'instant fais comme tu peux pour régler ce problème, à terme avec Guice qui permettra l'inversion des dépendances ce sera plus simple à gérer.

2021-08-28 15:46 UTC, Voltariuss commented on libraries/justice-hands/src/main/java/fr/fallenvaders/minecraft/justice_hands/sanctionmanager/SanctionsAlgo.java
> +    public static final int CFG_PATH_MUTE_MIN_POINT = CONFIG.getInt(CFG_PATH_POINT + ".mute-min-points");
Toujours pas bon. Ce qui est attendu : `public static final String CFG_PATH_MUTE_MIN_POINT = CFG_PATH_POINT + ".mute-min-points";
Et etc.

On fait ça cf. Commentaire précédent qui explique pourquoi créer une constante CONFIG est impossible avec Bukkit.

2021-08-28 15:46 UTC, Voltariuss commented on libraries/justice-hands/src/main/java/fr/fallenvaders/minecraft/justice_hands/sanctionmanager/SanctionsAlgo.java
> +    public static final long LONG_DAY = 24l * 60l * 60l * 1000l; // hour(24) * min(60) * sec(60) * ms(1000)
Indique le type de mesure de la valeur de la variable : genre `LONG_DAY_IN_MS`

2021-08-28 16:09 UTC, GlynixFR commented on libraries/justice-hands/src/main/java/fr/fallenvaders/minecraft/justice_hands/sanctionmanager/SanctionsAlgo.java
> +    public static final int CFG_PATH_MUTE_MIN_POINT = CONFIG.getInt(CFG_PATH_POINT + ".mute-min-points");
Je veux pas un string moi, je veux un int dans la config

2021-08-28 16:27 UTC, GlynixFR commented on libraries/justice-hands/src/main/java/fr/fallenvaders/minecraft/justice_hands/sanctionmanager/SanctionsAlgo.java
> +    public static final int CFG_PATH_MUTE_MIN_POINT = CONFIG.getInt(CFG_PATH_POINT + ".mute-min-points");
Ok c'est fixé

2021-08-28 16:32 UTC, Voltariuss approved these changes

2021-08-29 15:25 UTC, merged